// This file will be auto-generated by the db:gen-types:local script
// Run: bun run db:gen-types:local

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export type Database = {
    public: {
        Tables: {
            generated_content: {
                Row: {
                    id: string;
                    created_at: string;
                    updated_at: string;
                    title: string | null;
                    content: string | null;
                    content_type: string | null;
                    metadata: Json | null;
                    source_url: string | null;
                    repository_id: string | null;
                    organization_id: string | null;
                };
                Insert: {
                    id?: string;
                    created_at?: string;
                    updated_at?: string;
                    title?: string | null;
                    content?: string | null;
                    content_type?: string | null;
                    metadata?: Json | null;
                    source_url?: string | null;
                    repository_id?: string | null;
                    organization_id?: string | null;
                };
                Update: {
                    id?: string;
                    created_at?: string;
                    updated_at?: string;
                    title?: string | null;
                    content?: string | null;
                    content_type?: string | null;
                    metadata?: Json | null;
                    source_url?: string | null;
                    repository_id?: string | null;
                    organization_id?: string | null;
                };
                Relationships: [];
            };
        };
        Views: {
            [_ in never]: never;
        };
        Functions: {
            [_ in never]: never;
        };
        Enums: {
            [_ in never]: never;
        };
        CompositeTypes: {
            [_ in never]: never;
        };
    };
};
